#!/usr/bin/env node
const child_process = require("child_process");
const readline = require('readline');
const getData = async () => {
  return new Promise((resolve, reject) => {
    const lines = [];
    const rl = readline.createInterface({
      input: process.stdin,
    })
  
    rl.on('line', (line) => {
      lines.push(line);
    })
    
    rl.on('close', () => {
      resolve(lines)
    })

    rl.on('error', (line) => {
      reject(err)
    })
  })
}

const main = async () => {
  const stringData = await getData()
  const result = child_process.execSync("tasksidian add", {
    encoding : 'utf8',
    input: stringData[0]
  });
  process.stdout.write(result)
}

main()
